apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: apicontagemaspnet5 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apicontagemaspnet5 
    spec:
      containers:
        - name: apicontagemaspnet5 
          image: groffeazuredevops.azurecr.io/apicontagemaspnet5
          ports:
          - containerPort: 80